### ISSUE TITLE
Error get_provider_name

### ISSUE THREAD

**Issue by g0rp** [iignatov/LightOpenID#12] opened 2016-02-28 13:20 UTC
Hi,

I found a mistake inside the class. (v1.3.0 (2016-02-20))
line 690 : get_provider_name($this->claimed_id) == 'yahoo'

PHP said : Fatal error: Call to undefined function get_provider_name()
'$this' is missing. I added it and it's working perfectly now.

**Comment by g0rp** [comment] 2016-02-28 13:20
Oups I just saw the pull request with the same subject...

**Comment by Arthom** [comment] 2016-02-28 19:03
i merged the bugfix :)

you need to change get_provider_name to $this->get_provider_name

**Comment by iignatov** [comment] 2016-03-04 08:58
@Arthom, thanks for the PR!

**Comment by iignatov** [comment] 2016-03-04 09:28
Thanks for the notice, guys!

I don't use this library (or PHP at all) anymore, so I didn't have an environment to test the whole library after the change and only tested the function implementation itself in an online PHP-sandbox.

I merged the PR, the issue is now fixed.

**Closed by iignatov** 2016-03-04 09:28 UTC
